executables = fib_executable vector_executable matrix_executable
all: $(executables)
fib_executable: 
	g++ -L/home/harshit/fpp/assignment1/library/ -Wall -o fib fib.cpp -lstamp -lpthread
vector_executable: 
	g++ -L/home/harshit/fpp/assignment1/library/ -Wall -o vector vector.cpp -lstamp -lpthread
matrix_executable: 
	g++ -L/home/harshit/fpp/assignment1/library/ -Wall -o matrix matrix.cpp -lstamp -lpthread